---
# Below is a loop to add osp_servers
- name: add QA servers
  os_server:
    cloud: openstack
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    key_name: "{{ item.key_name }}"
    flavor: "{{ item.flavor }}"
    security_groups: "{{ item.security_group }}"
    delete_fip: yes
    wait: no
    nics: "{{ item.nics }}"
    meta: "{{ item.meta }}"
    userdata: "{{ item.userdata }}"
  loop: "{{ osp_servers }}"

# Below adds FIPs to qa servers
- name: add ext fip to qa servers
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: "{{ item.name }}"
    network: ext_network
    wait: true
    timeout: 200
  loop: "{{ osp_servers }}"

# Needs a wait
- name: Verify online @2 mins
  pause:
    minutes: 2
